name: CI

on: [pull_request]

jobs:
  basic:
    runs-on: ubuntu-latest

    env:
      FORCE_COLOR: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Run linter
        run: npm run lint
      - name: Run Jest
        env:
          IS_CI: true
          UCKEY: ${{ secrets.UCKEY }}
        run: npm test
      - name: Add Comment
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { readFile } = require('fs/promises')
            const template = ({ file, url }) => `
            <details>
              <summary>
                <strong>${file}</strong>
              </summary>

              ![${file}](${url})

            </details>
            `

            try {
              const data = await readFile('./snapshotresults.json')
              const { snapshots } = JSON.parse(data)
              const info = snapshots.map(snap => template(snap)).join('\n')

              if (info) {
                await github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: '**Diffs:**\n\n' + info
                })
              }
            } catch (error) {
              console.log(error)
            }
